FORMAT: 1A

# Kellen's API

API for front-end to database communication on the kellenschmidt.com family of websites

## API Homepage [/]

### View homepage [GET]

Display the homepage for the API with links to documentation and other resources.
Log page visit.

+ Request (application/json)

        {
            
        }
        
+ Response 200

        {
        
        }
        
## Page Visit Tracking [/page-visit]

### Track a page visit [POST]

Log ip address, browser, operating system of user as well as the time, site, and referrer whenever
a page on the kellenschmidt.com family of pages is visited.

+ Request (application/json)

        {
            "site": "urlshortener.kellenschmidt",
            "referrer": "https://kellenschmidt.com/"
        }
        
+ Response 200

        {
            "rows_affected": 1
        }
        
## View URLs [/urls]
        
### Get all visible urls [GET]

Return the code, long url, creation date, and count for all visible URLs.

+ Request (application/json)

    + Headers

            Authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJKUzI1NiJ9.IkFycmF5LkFycmF5Ig.benYhHwsq2d_tIQK7NPmwShr0sfchW9fYhneL0XM-1A

    + Body

            {
                
            }
        
+ Response 200

        {
            "data": [
                {
                    "code": "abc",
                    "user_id": 3,
                    "long_url": "https://github.com/mgechev/angular-seed/wiki/Deploying-prod-build-to-Apache-2/",
                    "date_created": "2017-03-24 09:35:16",
                    "count": 4,
                    "visible": "1"
                },
                {
                    "code": "123",
                    "user_id": 3,
                    "long_url": "https://arjunphp.com/creating-restful-api-slim-framework/",
                    "date_created": "2017-03-29 10:01:34",
                    "count": 1,
                    "visible": "1"
                },
                {
                    "code": "L0l",
                    "user_id": 3,
                    "long_url": "https://v4-alpha.getbootstrap.com/components/carousel/",
                    "date_created": "2017-04-05 03:57:15",
                    "count": 37,
                    "visible": "1"
                },
            ]
        }

## Short URLs [/url]

### Create new short URL [POST]

Given a long url, create a short url and add that data including creation date to database.
Log interaction.

+ Request (application/json)

    + Headers

            Authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJKUzI1NiJ9.IkFycmF5LkFycmF5Ig.benYhHwsq2d_tIQK7NPmwShr0sfchW9fYhneL0XM-1A

    + Body

            {
                "long_url": "https://github.com/mgechev/angular-seed/wiki/Deploying-prod-build-to-Apache-2"
            }
        
+ Response 200

        {
            "code": "abc",
            "user_id": 3,
            "long_url": "https://github.com/mgechev/angular-seed/wiki/Deploying-prod-build-to-Apache-2",
            "date_created": "2017-03-24 09:35:16",
            "count": 5
        }
        
### Remove short URL [PUT]

Change the visibility state to hidden thereby "deleting" a URL by hiding it from view 
even though it will still be functional.
Log interaction.

+ Request (application/json)

    + Headers

            Authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJKUzI1NiJ9.IkFycmF5LkFycmF5Ig.benYhHwsq2d_tIQK7NPmwShr0sfchW9fYhneL0XM-1A

    + Body

            {
                "code": "abc"
            }
        
+ Response 200

        {
            "rows affected": 1
        }
        
## Short URL click [/hit/{code}]

### Get long URL and increment URL hit count [POST]

Get the long URL for given short URL. Increment number of page visits for the page with the given code.
Log interaction.

+ Parameters
    + code - Short code of which URL was visited

+ Request (application/json)

        {
            
        }
        
+ Response 200

        {
            "long_url": "https://github.com/mgechev/angular-seed/wiki/Deploying-prod-build-to-Apache-2"
        }
        
## Register [/register]

### Register for an account [POST]

Create and account with a new user and generate a new token for that user and device

+ Request (application/json)

        {
            "email": "kobe@lakers.com",
            "name": "Kobe Bryant",
            "phone": 14567890432,
            "password": "ball_is_life24"
        }
        
+ Response 200

        {
            "token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJKUzI1NiJ9.IkFycmF5LkFycmF5Ig.benYhHwsq2d_tIQK7NPmwShr0sfchW9fYhneL0XM-1A",
            "user": {
                "email": "kobe@lakers.com",
                "name": "Kobe Bryant",
                "phone": 14567890432,
                "password": "$2y$10$aER2ZxRPxzi.rk/nfgmN0eng7XMM2hVwTRBv5SSxaQQYF1rty24E2",
                "creation_date": 1243235664,
                "updated_date": 1214565645,
                "verified_phone": 0
            }
        }
        
## Login [/login]

### Login to an account [POST]

Login to an existing account and create a new token for that user and device

+ Request (application/json)

        {
            "email": "kobe@lakers.com",
            "password": "ball_is_life24"
        }
        
+ Response 200

        {
            "token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJKUzI1NiJ9.IkFycmF5LkFycmF5Ig.benYhHwsq2d_tIQK7NPmwShr0sfchW9fYhneL0XM-1A",
            "user": {
                "email": "kobe@lakers.com",
                "name": "Kobe Bryant",
                "phone": 14567890432,
                "password": "$2y$10$aER2ZxRPxzi.rk/nfgmN0eng7XMM2hVwTRBv5SSxaQQYF1rty24E2",
                "creation_date": 1243235664,
                "updated_date": 1214565645,
                "verified_phone": 0
            }
        }

## Authenticate [/authenticate]

### Authenticate the current token [POST]

Test the token to confirm that it is valid for the given user and device

+ Request (application/json)

    + Headers

            Authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJKUzI1NiJ9.IkFycmF5LkFycmF5Ig.benYhHwsq2d_tIQK7NPmwShr0sfchW9fYhneL0XM-1A

    + Body

            {
                
            }
        
+ Response 200

        {
            "authenticated": true
        }
        
## IR Projects and Work Experience Cards [/cards/{type}]

### Get all cards of a type [GET]

Return information for each of the projects or work experience cards.

+ Parameters
    + type - Type of card to be displayed (0: Project, 1: Work Experience)

+ Request (application/json)

        {

        }
        
+ Response 200

        {
            "data": [
                {
                    "card_id": "1",
                    "id": "url-shortener",
                    "card_type": "0",
                    "title": "URL Shortener",
                    "caption": "Take long URLs and compress them into short links which are easy to share, tweet, email! Created entirely from scratch in both an Angular 2 version and a PHP version.",
                    "link": "",
                    "router_link": "/url-shortener",
                    "image_version": "1500603809",
                    "theme_color": "#FE993A",
                    "github_link": "https://github.com/kellenschmidt/kellenschmidt.com",
                    "description": "<h1>URL Shortener</h1><p>More content here...</p>"
                    "visible": 1
                }
            ]
        }
        
## IR Skills Chips [/chips]

### Get all of the chips [GET]

Return data for all of the skills chips ordered by category and seperated by rows with id of "category-name" and title of the category title.

+ Request (application/json)

        {

        }
        
+ Response 200

        {
            "data": [
                {
                    "chip_id": "0",
                    "id": "category-heading",
                    "title": "Languages",
                    "category": "languages",
                    "image_version": "",
                    "color": "",
                    "visible": "1"
                },
                {
                    "chip_id": "1",
                    "id": "html5",
                    "title": "HTML",
                    "category": "languages",
                    "image_version": "1500581805",
                    "color": "#9A9A9A",
                    "visible": "1"
                },
                {
                    "chip_id": "2",
                    "id": "css3",
                    "title": "CSS",
                    "category": "languages",
                    "image_version": "1500581806",
                    "color": "#9A9A9A",
                    "visible": "1"
                }
            ]
        }
        
## IR School Courses [/courses]

### Get all cards for courses carousel [GET]

Get data for carousel of courses. Grouped into three courses per array item. Three cards on each carousel screen.

+ Request (application/json)

        {

        }
        
+ Response 200

        {
            "data": [
                [
                    {
                        "course_id": "0",
                        "number": "CSE 5345",
                        "name": "Advanced App Programming",
                        "line_breaks": [
                            1
                        ],
                        "visible": "1"
                    },
                    {
                        "course_id": "1",
                        "number": "CSE 5323",
                        "name": "Mobile Apps for Sensing and Learning",
                        "line_breaks": [
                            0
                        ],
                        "visible": "1"
                    },
                    {
                        "course_id": "2",
                        "number": "CSE 4345",
                        "name": "Software Engineering Principles",
                        "line_breaks": [
                            0
                        ],
                        "visible": "1"
                    }
                ],
                [
                    {
                        "course_id": "3",
                        "number": "CSE 3330",
                        "name": "Database Concepts",
                        "line_breaks": [
                            2
                        ],
                        "visible": "1"
                    },
                    {
                        "course_id": "4",
                        "number": "CSE 2341",
                        "name": "Data Structures",
                        "line_breaks": [
                            2
                        ],
                        "visible": "1"
                    },
                    {
                        "course_id": "5",
                        "number": "CSE 3345",
                        "name": "Graphical User Interface Design",
                        "line_breaks": [
                            1
                        ],
                        "visible": "1"
                    }
                ]
            ]
        }